#DUBBOX
dubbox:
  application: 
    name: xbin-store-service-item
    organization: dubbox
    owner: binux
  registry: 
    protocol: zookeeper
    address: 192.168.125.128:2181
  annotation:
    package: cn.binux.item
  protocol:
    name: dubbo
    port: 20884
    host: 192.168.125.1
    timeout: 30000
    threadpool: fixed
    threads: 500
    accepts: 1000
    serialization: kryo
    optimizer: cn.binux.serial.SerializationOptimizerImpl
  monitor:
    enabled: false
    address: 192.168.125.1:6060
    username: admin
    password: admin

druid:
    url: jdbc:mysql://localhost:3306/xbin_store?characterEncoding=utf-8
    driver-class: com.mysql.jdbc.Driver
    username: root
    password: OZo+t9QET+ctzd5Esn9q0GJP5hXtWWIKEsX8c4/w6z4C4AnxrwpvySNgBS89XdazOavjXXZp0oeZtQ3P9lLGEA==
    initial-size: 1
    min-idle: 1
    max-active: 20
    test-on-borrow: true
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 1 FROM DUAL
    test-While-Idle: true
    test-on-return: false
    pool-prepared-statements: false
    max-pool-prepared-statement-per-connection-size: 20
    filters: stat,wall,log4j,config
    connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;config.decrypt=true
    monitor:
          enabled: false
          druid-stat-view: /druid/*
          druid-web-stat-filter: /*
          allow: 219.230.50.107,127.0.0.1
          deny: 192.168.1.73
          login-username: admin
          login-password: 123456
          exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
          reset-enable: false
mybatis:
    type-aliases-package: cn.binux.pojo
    mapper-locations: classpath:mapper/*.xml


pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

# Redis
redisKey:
  # 缓存时间 默认半小时
  expire_time: 1800
  prefix:
    item_info_profix: 'ITEM_INFO:'
  suffix:
    item_info_base_suffix: ':BASE'
    item_info_desc_suffix: ':DESC'


# 静态页面生成目录
static_html_path: /Volumes/HGST/IdeaProjects/xbin-store/xbin-store-service-item/item/

server:
  port: 8514
